# Generated by Django 6.0 on 2025-12-23 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Point",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=200)),
                ("contents", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="ListPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                (
                    "status",
                    models.TextField(
                        choices=[("D", "Delivered"), ("P", "Pending")], default="P"
                    ),
                ),
                (
                    "point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="syllabooster.point",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Syllabus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "points",
                    models.ManyToManyField(
                        through="syllabooster.ListPoint", to="syllabooster.point"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="listpoint",
            name="syllabus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="syllabooster.syllabus"
            ),
        ),
        migrations.AddField(
            model_name="point",
            name="tags",
            field=models.ManyToManyField(to="syllabooster.tag"),
        ),
        migrations.AlterUniqueTogether(
            name="listpoint",
            unique_together={("syllabus", "point")},
        ),
    ]
