# Generated by Django 6.0 on 2025-12-23 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("syllabooster", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ListPoint",
            new_name="SyllabusPoint",
        ),
    ]
