# Generated by Django 6.0 on 2025-12-23 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syllabooster", "0002_rename_listpoint_syllabuspoint"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name="syllabuspoint",
            name="status",
        ),
        migrations.CreateModel(
            name="CoursePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                (
                    "status",
                    models.TextField(
                        choices=[("D", "Delivered"), ("P", "Pending")], default="P"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="syllabooster.course",
                    ),
                ),
                (
                    "point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="syllabooster.point",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "unique_together": {("course", "point")},
            },
        ),
        migrations.AddField(
            model_name="course",
            name="points",
            field=models.ManyToManyField(
                through="syllabooster.CoursePoint", to="syllabooster.point"
            ),
        ),
    ]
