# Generated by Django 6.0 on 2025-12-24 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "syllabooster",
            "0003_course_remove_syllabuspoint_status_coursepoint_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("display_name", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="PointType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="coursepoint",
            name="status",
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="point",
            name="contents",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="syllabus",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name="coursepoint",
            name="state",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="course_points",
                to="syllabooster.deliverystate",
            ),
        ),
        migrations.AddField(
            model_name="deliverystate",
            name="point_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="states",
                to="syllabooster.pointtype",
            ),
        ),
        migrations.AddField(
            model_name="point",
            name="point_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="points",
                to="syllabooster.pointtype",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="deliverystate",
            unique_together={("point_type", "name")},
        ),
    ]
