# Generated by Django 6.0 on 2025-12-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "syllabooster",
            "0004_deliverystate_pointtype_remove_coursepoint_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverystate",
            name="position",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
