# Generated by Django 6.0 on 2025-12-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syllabooster", "0005_deliverystate_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverystate",
            name="css_class",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
