# Generated by Django 6.0 on 2025-12-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syllabooster", "0006_deliverystate_css_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointtype",
            name="icon",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
