# Generated by Django 6.0 on 2025-12-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syllabooster", "0007_pointtype_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="current_position",
            field=models.PositiveIntegerField(db_default=0),
        ),
    ]
