# Generated by Django 6.0 on 2025-12-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syllabooster", "0012_alter_coursepoint_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverystate",
            name="css_class",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
