# Generated by Django 6.0 on 2025-12-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syllabooster", "0013_alter_deliverystate_css_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="point",
            name="contents",
            field=models.TextField(
                blank=True,
                help_text="Write contents in MarkDown. Use $...$ for inline math and $$...$$ for display math.",
            ),
        ),
    ]
